version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      
    working_directory: ~/may-circleci

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
       run tests!
       this example uses Django's built-in test-runner
       other common Python testing frameworks include pytest and nose
       https://pytest.org
       https://nose.readthedocs.io
      - run:
          name: run static analysis
          command: |
            . venv/bin/activate
            python fizzbuzz.py
      - run:
          name: run tests
          command: |
              .venv/bin/activate
            python fizzbuzz.py
          
